FROM i386/ubuntu
#COPY ../../miniACS_V1_37/ /miniACS_V1_37/
#WORKDIR /miniACS_V1_37/
RUN apt-get update \
	&& apt-get install -y net-tools \
	vim

#RUN ["./Linux/acs", "-s", "./Linux/Download_New.lua"]
